# Generated by Django 4.2.2 on 2023-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfile',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='music_images/'),
        ),
    ]
